1、编写一个类ExceptionTest，在main方法中使用try、catch、finally
要求：
在try块中，分别编写被0除的代码、数组越界的代码、空指针代码
在catch块中，捕获以上代码所产生的异常，并且打印异常信息
在finally块中，打印一条提示语句

2、自定义一个异常子类（继承自Exception），并在自定义类（学生类或超市类中）的相应方法中声明要抛出的异常，在该方法体内，
抛出一个该异常对象。在测试类的main()方法中，调用该自定义方法，使用try/catch捕获该方法中抛出的异常。
